# Generated by Django 3.2.6 on 2022-03-29 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
    ]
